In [1]:
import numpy as np

from optim.functions.player_gain_expected_value import player_gain_expected_value
from optim.functions.player_gain_variance import player_gain_variance
from optim.functions.player_utility_kelly_criteria import player_utility_kelly_criteria
from optim.functions.player_utility_linear import player_utility_linear
from optim.functions.player_utility_sharp_ratio import player_utility_sharp_ratio

from optim.resolve.resolve_fik import resolve_fik



In [2]:
# Données d'exemple
M = 1  # Nombre d'événements
N = 2  # Nombre d'issues par événement

# Cotes et probabilités estimées pour chaque issue de chaque événement
o = np.random.rand(M, N) * 5  + 1 # Cotes aléatoires entre 1 et 5
r = np.random.rand(M, N)  # Probabilités aléatoires entre 0 et 1
r /= r.sum(axis=1, keepdims=True)  # Normaliser pour que la somme des probabilités pour chaque événement soit 1
#o = 1/r
print("Cotes:\n", o)
print("Probabilités:\n", r)

np.sum(1/o)


Cotes:
 [[1.89468098 5.75451331]]
Probabilités:
 [[0.38964374 0.61035626]]


0.701569981767552

In [3]:
result = resolve_fik(o, r, player_utility_kelly_criteria)
print(np.sum(result))
print(f'utility = {-player_utility_kelly_criteria(result, o, r)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[0.67854032 0.32145968]]
0.9999999999999997
utility = 0.3936933334718048
expected_value = 0.6299966583373005
ecart_type = 0.27515606519723673


In [4]:
result = resolve_fik(o, r, lambda f, o, r : player_utility_kelly_criteria(f, o, r, B=10))
print(np.sum(result))
print(f'utility = {-player_utility_kelly_criteria(result, o, r)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[0.17685648 0.05823023]]
0.23508671232676426
utility = 0.09499993375588256
expected_value = 0.09999992639542853
ecart_type = 2.837096566656198e-08


In [5]:
result = resolve_fik(o, r, player_utility_linear)
print(np.sum(result))
print(f'utility = {-player_utility_linear(result, o, r)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[0.65262453 0.34737547]]
0.9999999999999998
utility = 0.5636314878257669
expected_value = 0.7018884181317389
ecart_type = 0.371829168175349


In [6]:
result = resolve_fik(o, r, lambda f, o, r: player_utility_linear(f, o, r, l=0))
print(np.sum(result))
print(f'utility = {-player_utility_linear(result, o, r, l=0)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[1.11022302e-16 1.00000000e+00]]
0.9999999999999979
utility = 2.5123032334732565
expected_value = 2.5123032334732565
ecart_type = 2.806300356209206


In [7]:
result = resolve_fik(o, r, lambda f, o, r: player_utility_linear(f, o, r, l=1, B=1000))
print(np.sum(result))
print(f'utility = {-player_utility_linear(result, o, r, l=0)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[0.75220352 0.24779648]]
1.0
utility = 0.42565106775296335
expected_value = 0.42565106775296335
ecart_type = 0.00037182875394710456


In [8]:
result = resolve_fik(o, r, lambda f, o, r: player_utility_linear(f, o, r, l=1))
print(np.sum(result))
print(f'utility = {-player_utility_linear(result, o, r, l=0)}')
print(f'expected_value = {player_gain_expected_value(result, o, r)}')
#print(f'variance = {player_gain_variance(result, o, r)}')
print(f'ecart_type = {np.sqrt(player_gain_variance(result, o, r))}')

Répartition optimale de la bankroll:
[[0.65262453 0.34737547]]
0.9999999999999998
utility = 0.7018884181317389
expected_value = 0.7018884181317389
ecart_type = 0.371829168175349


In [9]:
result = resolve_fik(o, r, player_utility_sharp_ratio)
print(np.sum(result))

L'optimisation a échoué: Inequality constraints incompatible
None


c:\users\jdelavande\projects\optim-sportbet\optibet_lib\optibet_lib\optim\functions\player_utility_sharp_ratio.py:23: RuntimeWarning: invalid value encountered in scalar power
  U = E / V**0.5
