In [1]:
import numpy as np
from scipy.optimize import minimize

# Données d'exemple
M = 5  # Nombre d'événements
N = 3  # Nombre d'issues par événement

# Cotes et probabilités estimées pour chaque issue de chaque événement
o = np.random.rand(M, N) * 5  # Cotes aléatoires entre 1 et 5
r = np.random.rand(M, N)  # Probabilités aléatoires entre 0 et 1
r /= r.sum(axis=1, keepdims=True)  # Normaliser pour que la somme des probabilités pour chaque événement soit 1

# Fonction objectif à maximiser
def objectif(f):
    f = f.reshape(M, N)
    return -np.sum(f * (o * r - 1))



print(f'o = {o}')
print(f'r = {r}')

# Contraintes
constraints = []

# Contrainte : somme des fractions de la bankroll <= 1 pour chaque événement
constraints.append({'type': 'ineq', 'fun': lambda f : 1 - np.sum(f.reshape(M, N))})

# Contrainte : non-négativité
bounds = [(0, 1) for _ in range(M * N)]

# Solution initiale (répartition uniforme)
f0 = np.ones(M * N) / (M * N)

# Résolution de l'optimisation
result = minimize(objectif, f0, constraints=constraints, bounds=bounds)

# Résultats
if result.success:
    f_optimal = result.x.reshape(M, N)
    print("Répartition optimale de la bankroll:")
    print(f_optimal)
else:
    print("L'optimisation a échoué:", result.message)


o = [[0.13613104 1.41260384 3.46993996]
 [4.17353184 4.37799561 2.16455832]
 [3.2781791  0.62008532 3.35358614]
 [4.78759512 2.01632516 1.79051922]
 [2.49272923 1.13354585 2.75364867]]
r = [[0.37800839 0.28666093 0.33533067]
 [0.31976316 0.2672374  0.41299943]
 [0.29162635 0.19138492 0.51698873]
 [0.1838297  0.02728253 0.78888777]
 [0.01740006 0.51015155 0.47244839]]
Répartition optimale de la bankroll:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.29892962e-15 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.49400542e-16]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


In [25]:
import requests
sport = 'Soccer'
apiKey = API_KEY
regions = 'eu'
markets = 'h2h'
url = f'https://api.the-odds-api.com/v4/sports/{sport}/odds/?apiKey={apiKey}&regions={regions}&markets={markets}'

In [26]:
response = requests.get(url)

In [27]:
response.json()

[{'id': '51906a682c32df1067d2b7daaf5a35a5',
  'sport_key': 'soccer_uefa_europa_conference_league',
  'sport_title': 'UEFA Europa Conference League',
  'commence_time': '2024-07-24T15:00:00Z',
  'home_team': 'FC Struga',
  'away_team': 'FC Pyunik',
  'bookmakers': [{'key': 'pinnacle',
    'title': 'Pinnacle',
    'last_update': '2024-07-24T14:03:43Z',
    'markets': [{'key': 'h2h',
      'last_update': '2024-07-24T14:03:43Z',
      'outcomes': [{'name': 'FC Pyunik', 'price': 3.12},
       {'name': 'FC Struga', 'price': 2.37},
       {'name': 'Draw', 'price': 3.1}]}]},
   {'key': 'williamhill',
    'title': 'William Hill',
    'last_update': '2024-07-24T14:03:44Z',
    'markets': [{'key': 'h2h',
      'last_update': '2024-07-24T14:03:44Z',
      'outcomes': [{'name': 'FC Pyunik', 'price': 2.9},
       {'name': 'FC Struga', 'price': 2.2},
       {'name': 'Draw', 'price': 3.3}]}]},
   {'key': 'marathonbet',
    'title': 'Marathon Bet',
    'last_update': '2024-07-24T14:03:04Z',
    'market

In [37]:

import pandas as pd
def transform_data_to_df(data):
    flattened_data = []

    for match in data:
        for bookmaker in match['bookmakers']:
            for market in bookmaker['markets']:
                for outcome in market['outcomes']:
                    flattened_data.append({
                        'match_id': match['id'],
                        'sport_key': match['sport_key'],
                        'sport_title': match['sport_title'],
                        'commence_time': match['commence_time'],
                        'home_team': match['home_team'],
                        'away_team': match['away_team'],
                        'bookmaker_key': bookmaker['key'],
                        'bookmaker_title': bookmaker['title'],
                        'bookmaker_last_update': bookmaker['last_update'],
                        'market_key': market['key'],
                        'market_last_update': market['last_update'],
                        'outcome_name': outcome['name'],
                        'outcome_price': outcome['price']
                    })

    df = pd.DataFrame(flattened_data)
    return df

In [38]:
transform_data_to_df(response.json())

match_id                             sport_key  \
0    51906a682c32df1067d2b7daaf5a35a5  soccer_uefa_europa_conference_league   
1    51906a682c32df1067d2b7daaf5a35a5  soccer_uefa_europa_conference_league   
2    51906a682c32df1067d2b7daaf5a35a5  soccer_uefa_europa_conference_league   
3    51906a682c32df1067d2b7daaf5a35a5  soccer_uefa_europa_conference_league   
4    51906a682c32df1067d2b7daaf5a35a5  soccer_uefa_europa_conference_league   
..                                ...                                   ...   
295  d911e455e3847e9798a6ef1c020c02c2     soccer_argentina_primera_division   
296  d911e455e3847e9798a6ef1c020c02c2     soccer_argentina_primera_division   
297  d911e455e3847e9798a6ef1c020c02c2     soccer_argentina_primera_division   
298  d911e455e3847e9798a6ef1c020c02c2     soccer_argentina_primera_division   
299  d911e455e3847e9798a6ef1c020c02c2     soccer_argentina_primera_division   

                       sport_title         commence_time           home_team  \
0    UEFA Europa Conference League  2024-07-24T15:00:00Z           FC Struga   
1    UEFA Europa Conference League  2024-07-24T15:00:00Z           FC Struga   
2    UEFA Europa Conference League  2024-07-24T15:00:00Z           FC Struga   
3    UEFA Europa Conference League  2024-07-24T15:00:00Z           FC Struga   
4    UEFA Europa Conference League  2024-07-24T15:00:00Z           FC Struga   
..                             ...                   ...                 ...   
295   Primera División - Argentina  2024-07-24T20:15:00Z  Sarmiento de Junin   
296   Primera División - Argentina  2024-07-24T20:15:00Z  Sarmiento de Junin   
297   Primera División - Argentina  2024-07-24T20:15:00Z  Sarmiento de Junin   
298   Primera División - Argentina  2024-07-24T20:15:00Z  Sarmiento de Junin   
299   Primera División - Argentina  2024-07-24T20:15:00Z  Sarmiento de Junin   

       away_team    bookmaker_key     bookmaker_title bookmaker_last_update  \
0      FC Pyunik         pinnacle            Pinnacle  2024-07-24T14:03:43Z   
1      FC Pyunik         pinnacle            Pinnacle  2024-07-24T14:03:43Z   
2      FC Pyunik         pinnacle            Pinnacle  2024-07-24T14:03:43Z   
3      FC Pyunik      williamhill        William Hill  2024-07-24T14:03:44Z   
4      FC Pyunik      williamhill        William Hill  2024-07-24T14:03:44Z   
..           ...              ...                 ...                   ...   
295  Racing Club     betanysports        BetAnySports  2024-07-24T14:02:48Z   
296  Racing Club     betanysports        BetAnySports  2024-07-24T14:02:48Z   
297  Racing Club  livescorebet_eu  LiveScore Bet (EU)  2024-07-24T14:02:49Z   
298  Racing Club  livescorebet_eu  LiveScore Bet (EU)  2024-07-24T14:02:49Z   
299  Racing Club  livescorebet_eu  LiveScore Bet (EU)  2024-07-24T14:02:49Z   

    market_key    market_last_update        outcome_name  outcome_price  
0          h2h  2024-07-24T14:03:43Z           FC Pyunik           3.12  
1          h2h  2024-07-24T14:03:43Z           FC Struga           2.37  
2          h2h  2024-07-24T14:03:43Z                Draw           3.10  
3          h2h  2024-07-24T14:03:44Z           FC Pyunik           2.90  
4          h2h  2024-07-24T14:03:44Z           FC Struga           2.20  
..         ...                   ...                 ...            ...  
295        h2h  2024-07-24T14:02:48Z  Sarmiento de Junin           4.90  
296        h2h  2024-07-24T14:02:48Z                Draw           3.25  
297        h2h  2024-07-24T14:02:49Z         Racing Club           1.81  
298        h2h  2024-07-24T14:02:49Z  Sarmiento de Junin           4.60  
299        h2h  2024-07-24T14:02:49Z                Draw           3.20  

[300 rows x 13 columns]

In [30]:
[sport['sport_key'] for sport in response.json()]

['soccer_uefa_europa_conference_league',
 'soccer_uefa_europa_conference_league',
 'soccer_uefa_champs_league_qualification',
 'soccer_uefa_champs_league_qualification',
 'soccer_uefa_champs_league_qualification',
 'soccer_switzerland_superleague',
 'soccer_argentina_primera_division',
 'soccer_argentina_primera_division']

In [36]:
response.json()[2]

{'id': '179ff7d692c27ebe4f41023a5114bca3',
 'sport_key': 'soccer_uefa_champs_league_qualification',
 'sport_title': 'UEFA Champions League Qualification',
 'commence_time': '2024-07-24T17:30:00Z',
 'home_team': 'PAOK',
 'away_team': 'FK Borac Banja Luka',
 'bookmakers': [{'key': 'mybookieag',
   'title': 'MyBookie.ag',
   'last_update': '2024-07-24T14:03:45Z',
   'markets': [{'key': 'h2h',
     'last_update': '2024-07-24T14:03:45Z',
     'outcomes': [{'name': 'FK Borac Banja Luka', 'price': 15.25},
      {'name': 'PAOK', 'price': 1.18},
      {'name': 'Draw', 'price': 6.8}]}]},
  {'key': 'sport888',
   'title': '888sport',
   'last_update': '2024-07-24T14:03:07Z',
   'markets': [{'key': 'h2h',
     'last_update': '2024-07-24T14:03:07Z',
     'outcomes': [{'name': 'FK Borac Banja Luka', 'price': 15.0},
      {'name': 'PAOK', 'price': 1.13},
      {'name': 'Draw', 'price': 6.5}]}]},
  {'key': 'nordicbet',
   'title': 'Nordic Bet',
   'last_update': '2024-07-24T14:03:44Z',
   'markets': [

In [34]:
[bookie['bookmakers'] for bookie in response.json()[0]['bookmakers']]

KeyError: 'bookmakers'

In [24]:
url = f'https://api.the-odds-api.com/v4/sports/?apiKey={apiKey}'
response_sports = requests.get(url)
response_sports.json()

[{'key': 'americanfootball_cfl',
  'group': 'American Football',
  'title': 'CFL',
  'description': 'Canadian Football League',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_ncaaf',
  'group': 'American Football',
  'title': 'NCAAF',
  'description': 'US College Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_ncaaf_championship_winner',
  'group': 'American Football',
  'title': 'NCAAF Championship Winner',
  'description': 'US College Football Championship Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'americanfootball_nfl',
  'group': 'American Football',
  'title': 'NFL',
  'description': 'US Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_nfl_preseason',
  'group': 'American Football',
  'title': 'NFL Preseason',
  'description': 'US Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_nfl_super_bowl_winner',
  'group': 'American Football',
 

In [ ]:
sports = [{'key': 'americanfootball_cfl',
  'group': 'American Football',
  'title': 'CFL',
  'description': 'Canadian Football League',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_ncaaf',
  'group': 'American Football',
  'title': 'NCAAF',
  'description': 'US College Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_ncaaf_championship_winner',
  'group': 'American Football',
  'title': 'NCAAF Championship Winner',
  'description': 'US College Football Championship Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'americanfootball_nfl',
  'group': 'American Football',
  'title': 'NFL',
  'description': 'US Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_nfl_preseason',
  'group': 'American Football',
  'title': 'NFL Preseason',
  'description': 'US Football',
  'active': True,
  'has_outrights': False},
 {'key': 'americanfootball_nfl_super_bowl_winner',
  'group': 'American Football',
  'title': 'NFL Super Bowl Winner',
  'description': 'Super Bowl Winner 2024/2025',
  'active': True,
  'has_outrights': True},
 {'key': 'aussierules_afl',
  'group': 'Aussie Rules',
  'title': 'AFL',
  'description': 'Aussie Football',
  'active': True,
  'has_outrights': False},
 {'key': 'baseball_kbo',
  'group': 'Baseball',
  'title': 'KBO',
  'description': 'KBO League',
  'active': True,
  'has_outrights': False},
 {'key': 'baseball_milb',
  'group': 'Baseball',
  'title': 'MiLB',
  'description': 'Minor League Baseball',
  'active': True,
  'has_outrights': False},
 {'key': 'baseball_mlb',
  'group': 'Baseball',
  'title': 'MLB',
  'description': 'Major League Baseball',
  'active': True,
  'has_outrights': False},
 {'key': 'baseball_mlb_world_series_winner',
  'group': 'Baseball',
  'title': 'MLB World Series Winner',
  'description': 'World Series Winner 2024',
  'active': True,
  'has_outrights': True},
 {'key': 'basketball_nba_championship_winner',
  'group': 'Basketball',
  'title': 'NBA Championship Winner',
  'description': 'Championship Winner 2024/2025',
  'active': True,
  'has_outrights': True},
 {'key': 'basketball_ncaab_championship_winner',
  'group': 'Basketball',
  'title': 'NCAAB Championship Winner',
  'description': 'US College Basketball Championship Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'boxing_boxing',
  'group': 'Boxing',
  'title': 'Boxing',
  'description': 'Boxing Bouts',
  'active': True,
  'has_outrights': False},
 {'key': 'cricket_odi',
  'group': 'Cricket',
  'title': 'One Day Internationals',
  'description': 'One Day Internationals',
  'active': True,
  'has_outrights': False},
 {'key': 'cricket_t20_blast',
  'group': 'Cricket',
  'title': 'T20 Blast',
  'description': 'T20 Blast',
  'active': True,
  'has_outrights': False},
 {'key': 'cricket_test_match',
  'group': 'Cricket',
  'title': 'Test Matches',
  'description': 'International Test Matches',
  'active': True,
  'has_outrights': False},
 {'key': 'cricket_the_hundred',
  'group': 'Cricket',
  'title': 'The Hundred',
  'description': 'The Hundred',
  'active': True,
  'has_outrights': False},
 {'key': 'golf_masters_tournament_winner',
  'group': 'Golf',
  'title': 'Masters Tournament Winner',
  'description': '2025 Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'golf_pga_championship_winner',
  'group': 'Golf',
  'title': 'PGA Championship Winner',
  'description': '2025 Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'icehockey_nhl',
  'group': 'Ice Hockey',
  'title': 'NHL',
  'description': 'US Ice Hockey',
  'active': True,
  'has_outrights': False},
 {'key': 'icehockey_nhl_championship_winner',
  'group': 'Ice Hockey',
  'title': 'NHL Championship Winner',
  'description': 'Stanley Cup Winner 2024/2025',
  'active': True,
  'has_outrights': True},
 {'key': 'icehockey_sweden_hockey_league',
  'group': 'Ice Hockey',
  'title': 'SHL',
  'description': 'Swedish Hockey League',
  'active': True,
  'has_outrights': False},
 {'key': 'lacrosse_pll',
  'group': 'Lacrosse',
  'title': 'PLL',
  'description': 'Premier Lacrosse League',
  'active': True,
  'has_outrights': False},
 {'key': 'mma_mixed_martial_arts',
  'group': 'Mixed Martial Arts',
  'title': 'MMA',
  'description': 'Mixed Martial Arts',
  'active': True,
  'has_outrights': False},
 {'key': 'politics_us_presidential_election_winner',
  'group': 'Politics',
  'title': 'US Presidential Elections Winner',
  'description': '2024 US Presidential Election Winner',
  'active': True,
  'has_outrights': True},
 {'key': 'rugbyleague_nrl',
  'group': 'Rugby League',
  'title': 'NRL',
  'description': 'Aussie Rugby League',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_argentina_primera_division',
  'group': 'Soccer',
  'title': 'Primera División - Argentina',
  'description': 'Argentine Primera División',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_austria_bundesliga',
  'group': 'Soccer',
  'title': 'Austrian Football Bundesliga',
  'description': 'Austrian Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_belgium_first_div',
  'group': 'Soccer',
  'title': 'Belgium First Div',
  'description': 'Belgian First Division A',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_brazil_campeonato',
  'group': 'Soccer',
  'title': 'Brazil Série A',
  'description': 'Brasileirão Série A',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_brazil_serie_b',
  'group': 'Soccer',
  'title': 'Brazil Série B',
  'description': 'Campeonato Brasileiro Série B',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_chile_campeonato',
  'group': 'Soccer',
  'title': 'Primera División - Chile',
  'description': 'Campeonato Chileno',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_china_superleague',
  'group': 'Soccer',
  'title': 'Super League - China',
  'description': 'Chinese Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_conmebol_copa_libertadores',
  'group': 'Soccer',
  'title': 'Copa Libertadores',
  'description': 'CONMEBOL Copa Libertadores',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_denmark_superliga',
  'group': 'Soccer',
  'title': 'Denmark Superliga',
  'description': 'Danish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_efl_champ',
  'group': 'Soccer',
  'title': 'Championship',
  'description': 'EFL Championship',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_england_efl_cup',
  'group': 'Soccer',
  'title': 'EFL Cup',
  'description': 'League Cup',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_england_league1',
  'group': 'Soccer',
  'title': 'League 1',
  'description': 'EFL League 1',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_england_league2',
  'group': 'Soccer',
  'title': 'League 2',
  'description': 'EFL League 2 ',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_epl',
  'group': 'Soccer',
  'title': 'EPL',
  'description': 'English Premier League',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_fifa_world_cup_winner',
  'group': 'Soccer',
  'title': 'FIFA World Cup Winner',
  'description': 'FIFA World Cup Winner 2026',
  'active': True,
  'has_outrights': True},
 {'key': 'soccer_finland_veikkausliiga',
  'group': 'Soccer',
  'title': 'Veikkausliiga - Finland',
  'description': 'Finnish  Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_france_ligue_one',
  'group': 'Soccer',
  'title': 'Ligue 1 - France',
  'description': 'French Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_france_ligue_two',
  'group': 'Soccer',
  'title': 'Ligue 2 - France',
  'description': 'French Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_germany_bundesliga',
  'group': 'Soccer',
  'title': 'Bundesliga - Germany',
  'description': 'German Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_germany_bundesliga2',
  'group': 'Soccer',
  'title': 'Bundesliga 2 - Germany',
  'description': 'German Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_germany_liga3',
  'group': 'Soccer',
  'title': '3. Liga - Germany',
  'description': 'German Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_greece_super_league',
  'group': 'Soccer',
  'title': 'Super League - Greece',
  'description': 'Greek Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_italy_serie_a',
  'group': 'Soccer',
  'title': 'Serie A - Italy',
  'description': 'Italian Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_italy_serie_b',
  'group': 'Soccer',
  'title': 'Serie B - Italy',
  'description': 'Italian Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_korea_kleague1',
  'group': 'Soccer',
  'title': 'K League 1',
  'description': 'Korean Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_league_of_ireland',
  'group': 'Soccer',
  'title': 'League of Ireland',
  'description': 'Airtricity League Premier Division',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_netherlands_eredivisie',
  'group': 'Soccer',
  'title': 'Dutch Eredivisie',
  'description': 'Dutch Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_norway_eliteserien',
  'group': 'Soccer',
  'title': 'Eliteserien - Norway',
  'description': 'Norwegian Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_poland_ekstraklasa',
  'group': 'Soccer',
  'title': 'Ekstraklasa - Poland',
  'description': 'Polish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_portugal_primeira_liga',
  'group': 'Soccer',
  'title': 'Primeira Liga - Portugal',
  'description': 'Portugese Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_spain_la_liga',
  'group': 'Soccer',
  'title': 'La Liga - Spain',
  'description': 'Spanish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_spain_segunda_division',
  'group': 'Soccer',
  'title': 'La Liga 2 - Spain',
  'description': 'Spanish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_spl',
  'group': 'Soccer',
  'title': 'Premiership - Scotland',
  'description': 'Scottish Premiership',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_sweden_allsvenskan',
  'group': 'Soccer',
  'title': 'Allsvenskan - Sweden',
  'description': 'Swedish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_sweden_superettan',
  'group': 'Soccer',
  'title': 'Superettan - Sweden',
  'description': 'Swedish Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_switzerland_superleague',
  'group': 'Soccer',
  'title': 'Swiss Superleague',
  'description': 'Swiss Soccer',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_uefa_champs_league_qualification',
  'group': 'Soccer',
  'title': 'UEFA Champions League Qualification',
  'description': 'European Champions League Qualification',
  'active': True,
  'has_outrights': False},
 {'key': 'soccer_uefa_europa_conference_league',
  'group': 'Soccer',
  'title': 'UEFA Europa Conference League',
  'description': 'UEFA Europa Conference League',
  'active': True,
  'has_outrights': False}]